# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='max_temp',
            field=models.FloatField(default=0.0, verbose_name='Max'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='min_temp',
            field=models.FloatField(default=0.0, verbose_name='Min'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='rain',
            field=models.CharField(default='0%', max_length=200),
        ),
        migrations.AddField(
            model_name='forecast',
            name='wind',
            field=models.CharField(default='0km/h', max_length=200),
        ),
    ]
