# Generated by Django 2.0 on 2018-07-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0003_auto_20180724_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='region',
        ),
    ]
